### ISSUE TITLE
No space left on device 

### ISSUE THREAD

**Issue by askz** [fly-apps/fooocus-demo#1]
Hi,

it seems that the bootstrap script is unable to install required dependencies.

```
2024-04-02T19:19:27Z app[3d8dde9c9d6758] mad [info]ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
2024-04-02T19:19:27Z app[3d8dde9c9d6758] mad [info]WARNING: There was an error checking the latest version of pip.
2024-04-02T19:19:29Z app[3d8dde9c9d6758] mad [info]Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
2024-04-02T19:19:30Z app[3d8dde9c9d6758] mad [info]Collecting torch==2.1.0
2024-04-02T19:19:30Z app[3d8dde9c9d6758] mad [info]  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl (2200.6 MB)
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]     ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸             1.5/2.2 GB 162.4 MB/s eta 0:00:05
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]ERROR: Exception:
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]Traceback (most recent call last):
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]  File "/app/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]    yield
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]  File "/app/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]    data = self._fp_read(amt) if not fp_closed else b""
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]  File "/app/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]    return self._fp.read(amt) if amt is not None else self._fp.read()
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]  File "/app/venv/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 102, in read
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]    self.__buf.write(data)
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]  File "/usr/lib/python3.10/tempfile.py", line 622, in func_wrapper
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]    return func(*args, **kwargs)
2024-04-02T19:19:40Z app[3d8dde9c9d6758] mad [info]OSError: [Errno 28] No space left on device
```

```
root@3d8dde9c9d6758:/bootstrap# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda        7.8G  6.2G  1.2G  85% /
shm              16G     0   16G   0% /dev/shm
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/vdb         49G  3.7M   47G   1% /app/Fooocus/models
root@3d8dde9c9d6758:/bootstrap# du -sh /app/venv/
3.0G	/app/venv/
root@3d8dde9c9d6758:/bootstrap# %  
``` 

I'm not sure how to properly solve the issue 'the fly way'. But maybe creating another mount for the venv would be enough ? Let me know, I can contribute.

**Comment by kylemclaren** [comment]
@askz Hi, was this a GPU Machine? It doesn't look like it as there is only 8GB of rootfs — Fly GPU Machines have 50GB of rootfs

**Comment by askz** [comment]
Hello, can confirm the machine size: 

        performance-8x-cpu@32768MB

Can't tell if it's gpu, but I fired it with the command in the README of this project..

> fly launch --vm-gpu-kind a100-pcie-40gb --volume-initial-size 50

EDIT: gonna try again today.

**Comment by kylemclaren** [comment]
Looked up the Machine ID (should've done that initially) and it's not a GPU Machine. Not sure what went wrong there but you can try again with this new command:
```
fly launch --from https://github.com/fly-apps/fooocus-demo
```
(Running this requires the latest version of [flyctl](https://github.com/superfly/flyctl))
